APPLY_FIXES: all
DISABLE_LINTERS:
  - JSON_JSONLINT
  - SPELL_CSPELL
DISABLE_ERRORS_LINTERS:
  - COPYPASTE_JSCPD
  - SPELL_LYCHEE
FAIL_IF_UPDATED_SOURCES: true
GITHUB_STATUS_REPORTER: true
REPOSITORY_KICS_ARGUMENTS: --fail-on critical,high
SARIF_REPORTER: true
VALIDATE_ALL_CODEBASE: false
