[project]
name = "databricks-runtime-containers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jsonargparse>=4.40.0",
    "pip-requirements-parser>=32.0.1",
]
